<!DOCTYPE html>
<html>

<head>
    <title>Day Zero</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" />
</head>

<body link="#800080" bgcolor="#ffffff" text="#000080" vlink="#ff0000">
    <p align="center">
        <b>
            <font size="6">Hey,</font>
            <font size="4"></font>
            <font size="6">H</font>
            <font size="4">ow you doing?</font>
            <font size="2">
                <br>About Cloud & Programming<br>& Other Stuffs.
            </font>
            <br>
        </b>
        <font size="1">&nbsp;</font>
    </p>
    <div class="container is-fluid">
        <div class="tabs">
            <ul>
                <li><a href="../index.html">Home</a></li>
            </ul>
        </div>
        <article class="message is-dark">
            <div class="message-header">
                <p>TDD & Flask</p>
            </div>
            <div class="content">
                <div class="box"> 
                    $ mkdir kklist
                    $ python -m venv venv
                    $ .\venv\script\Activate
                    <br/>
                </div>

                 <div class="box">
                    <p>Create a file called title_tests.py and add following code snippet.</p>
                    <code style="white-space: pre-wrap">
    from selenium import webdriver

    browser = webdriver.Firefox()
    browser.get('http://localhost:5000/')
    assert 'Flask' in browser.title</code>
                </div>

                <div class="box">
                    <p>if you try to run this test case using following command:</p>
                    <blockquote>
                    > python .\functional_tests.py
                    </blockquote>
                    You will get following error:
                    <blockquote>
                        Traceback (most recent call last):
                        File "C:\work\langs\pw\projects\tdd\becracked\functional_tests.py", line 1, in <module>
                            from selenium import webdriver
                        ModuleNotFoundError: No module named 'selenium'
                    </blockquote>
                </div>
               
                <div class="box">
                    <p>It means you have to run following command:</p>

                    <blockquote>> pip install -U selenium</blockquote>

                    <p>Now after "selenium" module is installed and you try to run the test case again.</p>

                    <blockquote>(venv) .......\kklist> python.exe .\functional_tests.py</blockquote>
                    <p>
                        You will see that firefox browser gets launched and you get 404 error.
                        If you look at  terminal, you will get following error:
                    </p>
                    
                    <blockquote>
                        <pre>
    Traceback (most recent call last):
        File "C:\work\langs\pw\projects\tdd\becracked\functional_tests.py", line 4, in <module>
            browser.get('http://localhost:9090/')
        File "C:\work\langs\pw\projects\tdd\becracked\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in get
            self.execute(Command.GET, {"url": url})
        File "C:\work\langs\pw\projects\tdd\becracked\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
            self.error_handler.check_response(response)
        File "C:\work\langs\pw\projects\tdd\becracked\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
            raise exception_class(message, screen, stacktrace)
        selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A9090/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A9090.
        Stacktrace:
        RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
        WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
        UnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:832:5
        checkReadyState@chrome://remote/content/marionette/navigate.sys.mjs:58:24
        onNavigation@chrome://remote/content/marionette/navigate.sys.mjs:343:39
        emit@resource://gre/modules/EventEmitter.sys.mjs:148:20
                        </pre>
                    </blockquote>
                </div>

                <div class="box">
                    <p>This means flask application is not running and we need to install flask first,
                    and then start server to run render the home page. RUn below command to install flask.
                    </p>
                    <blockquote>pip install flask</blockquote>
                    
                    <p>You will see logs like below:</p>
                    <blockquote>
                        <pre>
        Collecting flask
    Using cached flask-3.0.3-py3-none-any.whl (101 kB)
    Collecting Werkzeug>=3.0.0
    Downloading werkzeug-3.0.4-py3-none-any.whl (227 kB)
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.6/227.6 kB 2.8 MB/s eta 0:00:00
    Collecting blinker>=1.6.2
    Using cached blinker-1.8.2-py3-none-any.whl (9.5 kB)
    Collecting click>=8.1.3
    Using cached click-8.1.7-py3-none-any.whl (97 kB)
    Collecting Jinja2>=3.1.2
    Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
    Collecting itsdangerous>=2.1.2
    Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
    Collecting colorama
    Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
    Collecting MarkupSafe>=2.0
    Using cached MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
    Installing collected packages: MarkupSafe, itsdangerous, colorama, blinker, Werkzeug, Jinja2, click, flask
    Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 Werkzeug-3.0.4 blinker-1.8.2 click-8.1.7 colorama-0.4.6 flask-3.0.3 itsdangerous-2.2.0

    [notice] A new release of pip is available: 23.0.1 -> 24.2
    [notice] To update, run: python.exe -m pip install --upgrade pip
                        </pre>
                    </blockquote>
                        
                    <p>It means all is good. And we can continue working on home page. </p>
                </div>

                <div class="box">
                    <p>Let's make a directory called 'kklist' where we will keep our backend application code.</p>
                    <blockquote>
                    > mkdir kklist 
                    > cd kklist
                    </blockquote>
                    
                    <p>So what happens when try to run below command:</p>
                    <blockquote>> flask --app kklapp run</blockquote>

                    <p>We get following error:</p>
                    <blockquote><pre>
    Usage: flask run [OPTIONS]
    Try 'flask run --help' for help.

    Error: Could not import 'kklapp'</pre>  
                    </blockquote>
                    
                    <p>This error is correct as we have not created kklapp.py module.</p>
                </div>

                <div class="box">
                    <p>So let create a file kklapp.py and try to run the above command once again:</p>
                    <blockquote>> flask --app kklapp run</blockquote>
                    
                    <p>We get DIFFRENT error this time:</p>

                    <blockquote>Failed to find Flask application or factory in module 'kklapp'. Use 'kklapp:name' to specify one.</blockquote> 
                    <p>
                    It means no flask application exists in kklapp.py module. So let's create one by adding below 
                    code in kklapp.py
                    </p>
                </div>

                <div class="box">
                    <code style="white-space: pre-wrap">
    from flask import Flask

    app = Flask(__name__)

    @app.route("/")
    def index():
        return '&lt;p&gt;Hello, World!&lt;/p&gt;'</code>
                </div>

                <div class="box">
                    <p>Now if we try to run the application again:</p>

                    <blockquote> kklist> flask --app kklapp run</blockquote>
                    <p>We get below message:</p>
                    <blockquote><pre>
    * Serving Flask app 'kklapp'
    * Debug mode: off
    WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
    * Running on http://127.0.0.1:5000
    Press CTRL+C to quit</pre></blockquote>
                </div>

                <div class="box">
                    <p>You will notice that we have not specified any port while starting our flask application & 
                    flask has started application at port 5000. If you get error like address already in use, 
                    then you can change it to some other port using --port flag like below:</p>

                    <blockquote> kklist> flask --app kklapp run --port 6001</blockquote>

                </div>

                <div class="box">
                    <p>Let's try to run our home test again. Open a terminal and go to kklist app location &
                    activate virtual environment again by running below command</p>

                    <blockquote> >..\venv\Scripts\activate</blockquote>

                    <p>This will show (venv) in front of your kklist path.</p>

                    <blockquote>(venv) .. \kklist> </blockquote>

                    <p>It means virtual environment has been actviated Successfully.</p>

                    <p>Now execute below command to run our home page test again.</p>

                    <blockquote>(venv) .. \kklist> python.exe ..\functional_tests.py</blockquote>
                </div>

                <div class="box">
                    <p>The above command will start firefox browser and open 'http://lcoalhost:5000' and display 
                    'hello world' at home page.</p>

                    <p>When you go back to terminal you will find below message:</p>
                    <blockquote><pre>
    (venv)..... \kklist> python.exe ..\functional_tests.py
    Traceback (most recent call last):
    File "C:\work\langs\pw\projects\tdd\becracked\functional_tests.py", line 5, in <module>
        assert 'Flask' in browser.title
    AssertionError
                </pre></blockquote>
                </div>

                <div class="box">
                    <p>The above means <title></title> tag does not have 'Flask' in its title. Hence the assertion failed.</p>

                    <p>If you look at kklapp.py module's index() method, you will notice that we are returning
                     '&lt;p&gt;Hello World&lt;/p&gt;' in response. Let's chane it to return below text:</p>

                    <blockquote>'&lt;html&gt;&lt;head&gt;&lt;title&gt;Flask&lt;/title&gt;&lt;/head&gt;&lt;body&gt;Hello world&lt;/body&gt;&lt;/html&gt;'</blockquote> 

                    <p>Restart the flask app again. </p>
                    
                    <blockquote>(venv) ...\kklist> flask --app kklapp run</blockquote>
                    
                    <p>and run the test case again.</p>

                    <blockquote>(venv)..... \kklist> python.exe ..\functional_tests.py</blockquote>
                    
                    <p>
                    This time we won't get any error and command will succeed without printing anything
                     on `terminal` or `console`.
                     </p>
                </div>

           </div>
          
        </article>

        
    </div>
    </div>
</body>

</html>

